name: Regression tests CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  k8s-tier1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes_version: [v1.19.14]
    steps:
      - name: Checkout tackle
        uses: actions/checkout@v2
        with:
          repository: konveyor/tackle
          path: tackle
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: v1.22.0
          kubernetes version: ${{ matrix.kubernetes_version }}
          start args: "--addons=registry --addons=ingress"
      - name: Validate Minikube
        run: minikube status | grep Running
      - name: Validate Cluster
        run: kubectl get nodes
      - name: Validate enabled addon in arg
        run: minikube addons list -o json | jq '.registry.Status' | grep enabled
      - name: Kubectl create namespace
        run: kubectl create ns tackle

      - name: Deploy tackle
        run: sleep 60s && kubectl create -f tackle/kubernetes/kubernetes-tackle.yaml -n tackle

      - name: Verify keycloak
        run: kubectl wait deployment/keycloak --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-controls
        run: kubectl wait deployment/tackle-controls --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-application-inventory
        run: kubectl wait deployment/tackle-application-inventory --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-pathfinder
        run: kubectl wait deployment/tackle-pathfinder --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-ui
        run: kubectl wait deployment/tackle-ui --for condition=available --timeout=-1s -n tackle

      - name: Wait for Ingress
        run: |
          bash -c 'external_ip="";
          while [ -z $external_ip ];
            do echo "Waiting for end point...";
            external_ip=$(kubectl get ingress tackle --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}" -n tackle);[ -z "$external_ip" ] &&
            sleep 10;
          done;
          echo "End point ready:" &&
          echo $external_ip;
          export endpoint=$external_ip;
          echo "CYPRESS_tackleUrl=https://$external_ip" >>$GITHUB_ENV'
     
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Install NPM
        run: npm install .
      - name: Run Tier1 test cases
        run: |
          npx cypress run --spec **/*.test.ts --env grepTags=@tier1,user=tackle,pass=password,tackleUrl=${{ env.CYPRESS_tackleUrl }}

  k8s-tier2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes_version: [v1.20.10]
    steps:
      - name: Checkout tackle
        uses: actions/checkout@v2
        with:
          repository: konveyor/tackle
          path: tackle
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: v1.22.0
          kubernetes version: ${{ matrix.kubernetes_version }}
          start args: "--addons=registry --addons=ingress"
      - name: Validate Minikube
        run: minikube status | grep Running
      - name: Validate Cluster
        run: kubectl get nodes
      - name: Validate enabled addon in arg
        run: minikube addons list -o json | jq '.registry.Status' | grep enabled
      - name: Kubectl create namespace
        run: kubectl create ns tackle

      - name: Deploy tackle
        run: sleep 60s && kubectl create -f tackle/kubernetes/kubernetes-tackle.yaml -n tackle

      - name: Verify keycloak
        run: kubectl wait deployment/keycloak --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-controls
        run: kubectl wait deployment/tackle-controls --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-application-inventory
        run: kubectl wait deployment/tackle-application-inventory --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-pathfinder
        run: kubectl wait deployment/tackle-pathfinder --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-ui
        run: kubectl wait deployment/tackle-ui --for condition=available --timeout=-1s -n tackle

      - name: Wait for Ingress
        run: |
          bash -c 'external_ip="";
          while [ -z $external_ip ];
            do echo "Waiting for end point...";
            external_ip=$(kubectl get ingress tackle --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}" -n tackle);[ -z "$external_ip" ] &&
            sleep 10;
          done;
          echo "End point ready:" &&
          echo $external_ip;
          export endpoint=$external_ip;
          echo "CYPRESS_tackleUrl=https://$external_ip" >>$GITHUB_ENV'
     
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Install NPM
        run: npm install .
      - name: Run Tier2 test cases
        run: |
          npx cypress run --spec **/*.test.ts --env grepTags=@tier2,user=tackle,pass=password,tackleUrl=${{ env.CYPRESS_tackleUrl }}
  
  k8s-tier3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes_version: [v1.21.4]
    steps:
      - name: Checkout tackle
        uses: actions/checkout@v2
        with:
          repository: konveyor/tackle
          path: tackle
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: v1.22.0
          kubernetes version: ${{ matrix.kubernetes_version }}
          start args: "--addons=registry --addons=ingress"
      - name: Validate Minikube
        run: minikube status | grep Running
      - name: Validate Cluster
        run: kubectl get nodes
      - name: Validate enabled addon in arg
        run: minikube addons list -o json | jq '.registry.Status' | grep enabled
      - name: Kubectl create namespace
        run: kubectl create ns tackle

      - name: Deploy tackle
        run: sleep 60s && kubectl create -f tackle/kubernetes/kubernetes-tackle.yaml -n tackle

      - name: Verify keycloak
        run: kubectl wait deployment/keycloak --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-controls
        run: kubectl wait deployment/tackle-controls --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-application-inventory
        run: kubectl wait deployment/tackle-application-inventory --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-pathfinder
        run: kubectl wait deployment/tackle-pathfinder --for condition=available --timeout=-1s -n tackle
      - name: Verify tackle-ui
        run: kubectl wait deployment/tackle-ui --for condition=available --timeout=-1s -n tackle

      - name: Wait for Ingress
        run: |
          bash -c 'external_ip="";
          while [ -z $external_ip ];
            do echo "Waiting for end point...";
            external_ip=$(kubectl get ingress tackle --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}" -n tackle);[ -z "$external_ip" ] &&
            sleep 10;
          done;
          echo "End point ready:" &&
          echo $external_ip;
          export endpoint=$external_ip;
          echo "CYPRESS_tackleUrl=https://$external_ip" >>$GITHUB_ENV'

      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Install NPM
        run: npm install .
      - name: Run Tier3 test cases
        run: |
          npx cypress run --spec **/*.test.ts --env grepTags=@tier3,user=tackle,pass=password,tackleUrl=${{ env.CYPRESS_tackleUrl }}
